name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Temporary solution: We will remove this after we publish the
    #                     GEO Knowledge Hub dependencies in the NPM Registry.
    - name: Start required services
      run: |
        ./docker/builder/start.sh

    - name: Install & Build
      run: |
        echo @geo-knowledge-hub:registry=http://127.0.0.1:4873 > ~/.npmrc

        npm --legacy-peer-deps install
        npm run build
  
    - name: Test
      run: npm test

    - name: Stop required services
      run: |
        ./docker/builder/finish.sh
